---
type: array
items:
  type: object
  additionalProperties: false
  required:
    - name
    - service
    - type
  properties:
    name:
      type: string
    service:
      type: string
    service_type:
      type: string
    type:
      type: string
      enum:
        - service
        - cloud-client
        - service-client
        - library
        - tool
        - baremetal
        - deployment
        - networking
        - other
    description:
      type: string
    has_install_guide:
      type: boolean
    has_api_guide:
      type: boolean
    has_api_ref:
      type: boolean
    has_config_ref:
      type: boolean
    has_in_tree_api_docs:
      type: boolean
    has_admin_guide:
      type: boolean
    has_user_guide:
      type: boolean
    has_in_tree_htaccess:
      type: boolean
    has_deployment_guide:
      type: boolean
